### ISSUE TITLE
Define a mechanism to enable dependency ordering between test methods

### ISSUE THREAD

**Issue by anujgandharv** [EaseTech/easytest-core#114]
There are valid Use Cases where dependency between tests needs to be defined. For eg. Imagine a bank account use case where an Account needs to be registered first before any check on that account can be performed. Thus AccountRegiterTest needs to be performed before AccountCheckTest.

EasyTest should provide a declarative mechanism to enable dependency ordering between tests.
Here is an initial set of requirements.

A user should be able to declare, at test method level, the tests on which it depends.

Here is how it could look like:

```
@RunWith.......
@DataLoader.......
public class TestClass {

       @Test 
       @DependsOn({"accountRegisterTest", "accountCheckTest"})
       public void accountDeleteTest(@param("name")String name) {
              .............
       }
}
```

The above should run the accountRegisterTest first, accountCheckTest second and accountDeleteTest third.

Complications: Since every test within EasyTest can run multiple times, it needs to be decided how to handle dependencies. Various options are:
1) Run each dependent test for as many times as its test data is defined for that test. Then run the test that defines the dependency.
2) Run all the tests (dependent as well as test that defines dependency) one at a time. 
3) Let the user decide on option one or two.
4) Any other option

**Comment by anujgandharv** [comment]
Further, there is also a need to share data between test method runs. EasyTest Should support a mechanism such that dependent tests can share there data with each other. 
Possibly define a boolean attribute on the dependsOn annotation that identifies whether the data should be shared between tests or not. There are further complications to this that will be listed soon.

**Comment by SiKing** [comment]
@anujgandharv  Have you seen `@FixMethodOrder(MethodSorters.NAME_ASCENDING)`, which comes with JUnit? It does not satisfy all your requirements, but I often use it in combination with EaseTest annotations.

**Comment by anujgandharv** [comment]
Good point Siking. I havent tested out with it but is definitely worth to check and have a look. Thanks for the pointer.

**Comment by SiKing** [comment]
Also might be worth looking at TestNG, which already does what you describe. But that is a complete replacement for JUnit.
