### ISSUE TITLE
Working with springboot application

### ISSUE THREAD

**Issue by mozinrat** [EaseTech/easytest-core#115]
Can you publish a demo unit test which works with spring boot application. Please mention if we need to exclude spring-boot-starter-test dependency to use this or we can exclude just junit.
Does it work with Mockito or has something like inbuilt.

**Comment by anujgandharv** [comment]
Sure. I can definitely try to publish that. I am assuming that you are already using easytest-spring library and not just easytest-core. Is that the correct assumption?

**Comment by mozinrat** [comment]
I had referred this https://github.com/EaseTech/easytest-spring/blob/master/src/test/java/org/easetech/easytest/example/TestExcelDataLoader.java for initial setup, tried testing with an autowired dependency but it threw NPE.

**Comment by anujgandharv** [comment]
Hi Rohit,
Please refer this example : https://github.com/EaseTech/easytest-samples/blob/master/src/test/java/org/easetech/easytest/spring/example/TestSpringConfiguration.java

and this wiki page for details : https://github.com/EaseTech/easytest/wiki/EasyTest-:-Spring-Integration

The one you refered is for easytest-core project. Notice the difference in the Runner class.

**Comment by anujgandharv** [comment]
Hi Rohit,
 were you able to get it working?

**Comment by mozinrat** [comment]
Hi Anuj,

Thanks it work for me. You are the man, I really like this. Do let me know
if I can contribute in any way.

Rohit

**Comment by anujgandharv** [comment]
HI Rohit,
I am glad it works for you. There are quite a few ways you can contribute to EasyTest project. 
1) You can contribute more Loader implementations to the project. For example, one thing that I have been wanting to do is to create a StreamLoader that continuously takes the input test data from an Input  Stream source, pass it to the test methods and return the result as output stream. This is mainly to add support for Load Testing and System Testing. 

2) If the above sounds too complicated, you can start by simply writing a JSON Loader, that loads data from JSON inout source and outputs as JSON documents.

3) Further, you can start by blogging and/or sharing your experience with EasyTest in your project. This would help build the community around EasyTest and would greatly help the project.

Let me know how much time you can spend on this and I can accordingly guide you further.

Thanks,
Anuj Kumar

**Comment by pebelsberger** [comment]
Should this issue be closed?
