### ISSUE TITLE
Is it possible to make tests from test file inputs from DataLoader run in parallel?

### ISSUE THREAD

**Issue by TeamAngelLab** [EaseTech/easytest-core#116]
Hello,

Is it possible to make tests from test file inputs from DataLoader run in parallel? Here is my use case:

I have bunch of tests provided in different CSV input data. All the tests in different CSV input data are isolated. That means tests provided in dataSource_A.csv doesn't depend on tests provided in dataSource_B.csv. But tests provided in each individual CSV should run serially in a single thread.
# More details:

Here are two CSV input data:

dataSource_A.csv:
test1
test2
test3

dataSource_B.csv:
test1
test2
test3
test4

dataSource_A.csv and dataSource_B.csv is provided in DataLoader annotation. Currently easytest aggregates all the tests together and runs them in number of threads provided in Parallel annotation. I would like to have them run in parallel threads but each thread dedicated for individual CSV. First thread should be associated with dataSource_A.csv and second thread should be associated dataSource_B.csv

Please let me know if you need any additional details.

Thanks,
Amar

**Comment by anujgandharv** [comment]
Hi Amar,
 It is possible to achieve such a use case using EasyTest. Here is how you can achieve it.
Create two test classes, one for each of your CSV file.
Then define them in a test suite(@BaseSuite annotation of EasyTest) and annotate your test suite with @ParallelSuite annotation.
What this essentially will do is run your two test classes in parallel and yet run all methods within each test class in serial.

Hope this helps. Let me know if you need more information or if you feel that explanation is not enough.

Thanks,
Anuj Kumar

**Comment by TeamAngelLab** [comment]
Thanks Anuj. We have multiple CSVs like 15 to 20 and it will scale whenever we have to write new test scenarios so creating separate test class per CSV is not a viable solution for us. All CSV goes through same single junit test method so can creating a new test class for every CSV is not viable solution considering it is going to duplicate stuff.

Is it possible to pass CSV file name in ParallelSuite Annotation?

Thanks,
Amar

**Comment by anujgandharv** [comment]
Hi . It is possible to provide the namesolution of test file as system property. Look at the Readme section : What's new in sectionew 1.2.2 
For details.
