### ISSUE TITLE
Why include poi-examples?

### ISSUE THREAD

**Issue by SiKing** [EaseTech/easytest-core#135]
I am looking at easytest-core:1.4.0 which includes the package org.apache.poi:poi-examples:3.8. I am wondering: why? This seems to be just bloat. Am I wrong?

**Comment by anujgandharv** [comment]
Hi,
 You could be right. I havent done thorough checking of the packages included in easytest. I would be happy to have a pull request that improve the library.

**Comment by SiKing** [comment]
Created a pull request.
